--[[
    init.lua
    Created: 02/07/2023 08:17:00
    Description: Autogenerated script file for the map morpond_cursed.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local morpond_cursed = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---morpond_cursed.Init
--Engine callback function
function morpond_cursed.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---morpond_cursed.Enter
--Engine callback function
function morpond_cursed.Enter(map)

  GAME:FadeIn(20)

end

---morpond_cursed.Exit
--Engine callback function
function morpond_cursed.Exit(map)


end

---morpond_cursed.Update
--Engine callback function
function morpond_cursed.Update(map)


end

---morpond_cursed.GameSave
--Engine callback function
function morpond_cursed.GameSave(map)


end

---morpond_cursed.GameLoad
--Engine callback function
function morpond_cursed.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return morpond_cursed

