--[[
    init.lua
    Created: 04/22/2023 18:26:27
    Description: Autogenerated script file for the map mismagius_detective_office.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mismagius_detective_office = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mismagius_detective_office.Init(map)
--Engine callback function
function mismagius_detective_office.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---mismagius_detective_office.Enter(map)
--Engine callback function
function mismagius_detective_office.Enter(map)

  GAME:FadeIn(20)

end

---mismagius_detective_office.Exit(map)
--Engine callback function
function mismagius_detective_office.Exit(map)


end

---mismagius_detective_office.Update(map)
--Engine callback function
function mismagius_detective_office.Update(map)


end

---mismagius_detective_office.GameSave(map)
--Engine callback function
function mismagius_detective_office.GameSave(map)


end

---mismagius_detective_office.GameLoad(map)
--Engine callback function
function mismagius_detective_office.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mismagius_detective_office

