--[[
	init.lua
	Created: 11/23/2022 17:13:47
	Description: Autogenerated script file for the map crystal_cave_end.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local crystal_cave_end = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--	  local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---CURMAPSCR.Init
--Engine callback function
function crystal_cave_end.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---CURMAPSCR.Enter
--Engine callback function
function crystal_cave_end.Enter(map)

  local mikon = CH('Mikon')
  GROUND:Hide('Mikon')
  GAME:FadeIn(20)
  if SV.global_quest.StoryProgression == 2 then
	local player = CH('PLAYER')
	GAME:CutsceneMode(true)
	UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_000']))
	SOUND:PlayBattleSE("DUN_Aurora_Beam_2")
	GAME:FadeOut(true,10)
	GROUND:Unhide('Mikon')
	GAME:FadeIn(10)
	UI:SetSpeaker(mikon)
	UI:BeginChoiceMenu(STRINGS:Format(MapStrings['Mikon_001']),
	{STRINGS:Format(MapStrings['Answer_A']),
	STRINGS:Format(MapStrings['Answer_B'])}, 1, 2)
	UI:WaitForChoice()
	result = UI:ChoiceResult()
	if result == 1 then
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_002_A']))
	else
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_002_B_1']))
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_002_B_2']))
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_002_B_3']))
	end
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_003']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_004']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_005']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_006']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_007']))
	UI:ResetSpeaker()
	GAME:FadeOut(true,60)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['String_1']))
	GAME:FadeIn(30)
	COMMON.GiftItem(player, RogueEssence.Dungeon.InvItem("apricorn_green"))
	COMMON.GiftItem(player, RogueEssence.Dungeon.InvItem("apricorn_red"))
	COMMON.GiftItem(player, RogueEssence.Dungeon.InvItem("apricorn_blue"))
	UI:SetSpeaker(mikon)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_008']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_009']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Mikon_010']))
	GAME:FadeOut(true,10)
	GROUND:Hide('Mikon')
	GAME:FadeIn(10)
	UI:ResetSpeaker()
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['String_3']))
	SV.global_quest.StoryProgression = 3
	GAME:CutsceneMode(false)
  end

end

---CURMAPSCR.Exit
--Engine callback function
function crystal_cave_end.Exit(map)


end

---CURMAPSCR.Update
--Engine callback function
function crystal_cave_end.Update(map)


end

---CURMAPSCR.GameSave
--Engine callback function
function crystal_cave_end.GameSave(map)


end

---CURMAPSCR.GameLoad
--Engine callback function
function crystal_cave_end.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function crystal_cave_end.VSEvent_Touch(obj, activator)
  if SV.global_quest.StoryProgression < 2 then
	GAME:CutsceneMode(true)
	local player = CH('PLAYER')
	GROUND:MoveToPosition(player, 244, 244, false, 2)
	GROUND:CharAnimateTurn(player, Direction.Left, 4, true)
	GAME:WaitFrames(18)
	GROUND:CharAnimateTurn(player, Direction.Right, 4, false)
	GAME:WaitFrames(18)
	GROUND:CharAnimateTurn(player, Direction.Up, 4, true)
	GAME:WaitFrames(45)
	GROUND:CharSetEmote(player, "exclaim", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['String_0']))
	GAME:FadeOut(false,20)
	GAME:CutsceneMode(false)
	GAME:ContinueDungeon('nad_crystal_cave', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
  end
end

function crystal_cave_end.Warp_Touch(obj, activator)
  SOUND:PlayBattleSE("DUN_Aurora_Beam_2")
  SOUND:FadeOutBGM()
  GAME:FadeOut(true,60)
  GAME:FadeOut(false,20)
  GAME:WaitFrames(30)
  COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'td_throwback_land', -1, 0, 0)
end

function crystal_cave_end.Stairs_Touch(obj, activator)
  UI:ResetSpeaker()
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['String_4']))
end

return crystal_cave_end