--[[
    init.lua
    Created: 12/12/2022 17:52:18
    Description: Autogenerated script file for the map amusement_castle_ruins.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local amusement_castle_ruins = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---CURMAPSCR.Init
--Engine callback function
function amusement_castle_ruins.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---CURMAPSCR.Enter
--Engine callback function
function amusement_castle_ruins.Enter(map)

  GAME:FadeIn(20)

end

---CURMAPSCR.Exit
--Engine callback function
function amusement_castle_ruins.Exit(map)


end

---CURMAPSCR.Update
--Engine callback function
function amusement_castle_ruins.Update(map)


end

---CURMAPSCR.GameSave
--Engine callback function
function amusement_castle_ruins.GameSave(map)


end

---CURMAPSCR.GameLoad
--Engine callback function
function amusement_castle_ruins.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function amusement_castle_ruins.Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("amusement_park", "entrance_north")
end

function amusement_castle_ruins.DungeonStair_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
end

return amusement_castle_ruins

