--[[
    init.lua
    Created: 06/24/2023 01:28:43
    Description: Autogenerated script file for the map event_playerwishcave.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local event_playerwishcave = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_playerwishcave.Init(map)
--Engine callback function
function event_playerwishcave.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_playerwishcave.Enter(map)
--Engine callback function
function event_playerwishcave.Enter(map)

  GAME:FadeIn(20)

end

---event_playerwishcave.Exit(map)
--Engine callback function
function event_playerwishcave.Exit(map)


end

---event_playerwishcave.Update(map)
--Engine callback function
function event_playerwishcave.Update(map)


end

---event_playerwishcave.GameSave(map)
--Engine callback function
function event_playerwishcave.GameSave(map)


end

---event_playerwishcave.GameLoad(map)
--Engine callback function
function event_playerwishcave.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return event_playerwishcave

