--[[
    init.lua
    Created: 03/04/2023 09:10:30
    Description: Autogenerated script file for the map mpc_enslaved.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mpc_enslaved = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mpc_enslaved.Init
--Engine callback function
function mpc_enslaved.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---mpc_enslaved.Enter
--Engine callback function
function mpc_enslaved.Enter(map)

  GAME:FadeIn(20)

end

---mpc_enslaved.Exit
--Engine callback function
function mpc_enslaved.Exit(map)


end

---mpc_enslaved.Update
--Engine callback function
function mpc_enslaved.Update(map)


end

---mpc_enslaved.GameSave
--Engine callback function
function mpc_enslaved.GameSave(map)


end

---mpc_enslaved.GameLoad
--Engine callback function
function mpc_enslaved.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mpc_enslaved

