--[[
    init.lua
    Created: 08/28/2023 12:04:06
    Description: Autogenerated script file for the map hauntedzone_entrance.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local hauntedzone_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---hauntedzone_entrance.Init(map)
--Engine callback function
function hauntedzone_entrance.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---hauntedzone_entrance.Enter(map)
--Engine callback function
function hauntedzone_entrance.Enter(map)

  GAME:FadeIn(20)

end

---hauntedzone_entrance.Exit(map)
--Engine callback function
function hauntedzone_entrance.Exit(map)


end

---hauntedzone_entrance.Update(map)
--Engine callback function
function hauntedzone_entrance.Update(map)


end

---hauntedzone_entrance.GameSave(map)
--Engine callback function
function hauntedzone_entrance.GameSave(map)


end

---hauntedzone_entrance.GameLoad(map)
--Engine callback function
function hauntedzone_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return hauntedzone_entrance

