--[[
    init.lua
    Created: 03/13/2023 16:21:06
    Description: Autogenerated script file for the map td_apramunem.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_apramunem = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---CURZONESCR.Init
--Engine callback function
function td_apramunem.Init(zone)


end

---CURZONESCR.EnterSegment
--Engine callback function
function td_apramunem.EnterSegment(zone, rescuing, segmentID, mapID)


end

---CURZONESCR.ExitSegment
--Engine callback function
function td_apramunem.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---CURZONESCR.Rescued
--Engine callback function
function td_apramunem.Rescued(zone, name, mail)


end

return td_apramunem

