--[[
    init.lua
    Created: 02/04/2023 10:40:55
    Description: Autogenerated script file for the map davigny_oceanroom.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local davigny_oceanroom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---davigny_oceanroom.Init
--Engine callback function
function davigny_oceanroom.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---davigny_oceanroom.Enter
--Engine callback function
function davigny_oceanroom.Enter(map)

  if SV.global_quest.StoryProgression == 16 then
    GAME:UnlockDungeon("td_watertomb")
	local coro1 = TASK:BranchCoroutine(function() davigny_oceanroom.Move1(CH('Powwene')) end)
	local coro2 = TASK:BranchCoroutine(function() davigny_oceanroom.Move1(CH('Smoochum')) end)
	GAME:FadeIn(20)
	TASK:JoinCoroutines({coro1,coro2})
	GROUND:Hide('Powwene')
	GROUND:Hide('Smoochum')
	SV.global_quest.StoryProgression = 17
  else
    GROUND:Hide('Powwene')
	GROUND:Hide('Smoochum')
	GAME:FadeIn(20)
  end

end

---davigny_oceanroom.Exit
--Engine callback function
function davigny_oceanroom.Exit(map)


end

---davigny_oceanroom.Update
--Engine callback function
function davigny_oceanroom.Update(map)


end

---davigny_oceanroom.GameSave
--Engine callback function
function davigny_oceanroom.GameSave(map)


end

---davigny_oceanroom.GameLoad
--Engine callback function
function davigny_oceanroom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function davigny_oceanroom.Move1(character)
  character.CollisionDisabled = true
  GROUND:MoveToPosition(character, 342, 199, false, 2)
end

function davigny_oceanroom.DungeonEntrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.global_quest.StoryProgression > 16 then
    local dungeon_entrances = {'td_watertomb'}
    local ground_entrances = {}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
  else
    UI:SetSpeaker(CH('Powwene'))
	UI:SetSpeakerEmotion("Worried")
	UI:ChoiceMenuYesNo(STRINGS:Format(MapStrings['Powwene_0'], SV.playername), false)
    UI:WaitForChoice()
    ch = UI:ChoiceResult()
    if ch then
      UI:SetSpeakerEmotion("Determined")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
      GAME:FadeOut(false, 20)
      GAME:EnterDungeon('td_watertomb', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, false, true)
    end
  end
end

function davigny_oceanroom.Purrloin_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Purrloin_0']))
  UI:SetSpeakerEmotion("Surprised")
  if SV.global_quest.StoryProgression > 12 then
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Purrloin_3']))
    UI:SetSpeakerEmotion("Shouting")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Purrloin_4']))
  else
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Purrloin_1']))
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Purrloin_2']))
  end
end

function davigny_oceanroom.Patrat_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Normal")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Patrat_0']))
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Patrat_1']))
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Patrat_2']))
end

function davigny_oceanroom.Phantump_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Sad")
  if SV.global_quest.StoryProgression > 15 then
    UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_4']))
    UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_5']))
  elseif SV.global_quest.StoryProgression > 14 then
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_2']))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_3']))
  else
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_0']))
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Phantump_1']))
  end
end

function davigny_oceanroom.Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("davigny", "EntranceOut")
end

function davigny_oceanroom.Sign_Action(obj, activator)
  UI:ResetSpeaker()
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Sign_0']))
end

return davigny_oceanroom

