--[[
    init.lua
    Created: 12/28/2022 16:05:20
    Description: Autogenerated script file for the map bigbridge_midpoint.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local bigbridge_midpoint = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---bigbridge_midpoint.Init
--Engine callback function
function bigbridge_midpoint.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---bigbridge_midpoint.Enter
--Engine callback function
function bigbridge_midpoint.Enter(map)

  GAME:FadeIn(20)

end

---bigbridge_midpoint.Exit
--Engine callback function
function bigbridge_midpoint.Exit(map)


end

---bigbridge_midpoint.Update
--Engine callback function
function bigbridge_midpoint.Update(map)


end

---bigbridge_midpoint.GameSave
--Engine callback function
function bigbridge_midpoint.GameSave(map)


end

---bigbridge_midpoint.GameLoad
--Engine callback function
function bigbridge_midpoint.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return bigbridge_midpoint

