--[[
    init.lua
    Created: 03/15/2023 12:05:45
    Description: Autogenerated script file for the map lot_emolga.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local lot_emolga = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---lot_emolga.Init(map)
--Engine callback function
function lot_emolga.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---lot_emolga.Enter(map)
--Engine callback function
function lot_emolga.Enter(map)

  GROUND:Hide("Powwene")
  if SV.sidequest.quest03 < 2 or SV.sidequest.quest03 > 3 then
    GROUND:Hide("Hoppip")
  elseif SV.sidequest.quest03 == 3 then
	GROUND:CharSetAnim(CH("Emolga"),"Sleep",true)
	GROUND:TeleportTo(CH("Hoppip"), 210, 98, Direction.Left)
  end
  if SV.lot_emolga == nil then
    SV.hiddensidequest.celebi = 0
    SV.lot_emolga =
	{
	  greeted = false,
	  talkshrine = false,
	  chat = 0
	}
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(30)
	UI:WaitHideTitle(20)
  end
  GAME:FadeIn(20)

end

---lot_emolga.Exit(map)
--Engine callback function
function lot_emolga.Exit(map)


end

---lot_emolga.Update(map)
--Engine callback function
function lot_emolga.Update(map)


end

---lot_emolga.GameSave(map)
--Engine callback function
function lot_emolga.GameSave(map)


end

---lot_emolga.GameLoad(map)
--Engine callback function
function lot_emolga.GameLoad(map)
  
  if SV.sidequest.quest03 == 3 then
	GROUND:CharSetAnim(CH("Emolga"),"Sleep",true)
  end
  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function lot_emolga.Exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("overworld", "Spawn_3")
end

function lot_emolga.TreasureBox_Action(chara, activator)
  if SV.sidequest.quest03 == 3 then
    UI:ResetSpeaker()
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_0']))
	if SV.emolgadiary == 0 then
	  SOUND:PlayFanfare("Fanfare/SpecialItem")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_1']))
	  SV.emolgadiary = 1
	else
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_2']))
	end
  else
    local emolga = CH('Emolga')
	GROUND:CharTurnToChar(emolga,CH('PLAYER'))
	UI:SetSpeaker(emolga)
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_9']))
  end
end

function lot_emolga.House_Touch(chara, activator)
  if SV.sidequest.quest03 > 2 then
    local dungeon_entrances = {'td_tinytillies'}
    local ground_entrances = {}
    COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
  else
    local emolga = CH('Emolga')
	GROUND:CharTurnToChar(emolga,CH('PLAYER'))
	UI:SetSpeaker(emolga)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_10']))
  end
end

function lot_emolga.Hoppip_Action(chara, activator)
  UI:SetSpeaker(chara)
  if SV.sidequest.quest03 == 2 then
    local emolga = CH("Emolga")
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_0']))
	GROUND:CharTurnToChar(chara,CH('PLAYER'))
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_1']))
    GAME:FadeOut(false, 20)
	SOUND:PlayBattleSE("DUN_Stun_Spore")
    GAME:WaitFrames(60)
    SV.sidequest.quest03 = 3
    GROUND:CharSetAnim(emolga,"Sleep",true)
	GAME:UnlockDungeon("td_tinytillies")
    GAME:FadeIn(20)
	UI:SetSpeaker(emolga)
	UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_11']))
	chara.CollisionDisabled = true
	GROUND:MoveInDirection(chara, Direction.Right, 24, false, 2)
	GROUND:CharAnimateTurn(chara, Direction.Left, 4, true)
	chara.CollisionDisabled = false
	UI:SetSpeaker(chara)
	UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_2']))
	UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_3']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_4']))
  else
    GROUND:CharTurnToChar(chara,CH('PLAYER'))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Hoppip_4']))
  end
end

function lot_emolga.Emolga_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  if SV.sidequest.quest03 > 3 then
    UI:SetSpeaker(chara)
	if SV.lot_emolga.chat > 0 then
	  UI:SetSpeakerEmotion("Pain")
      UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_15']))
	else
	  UI:SetSpeakerEmotion("Surprised")
      UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_12']))
      UI:SetSpeakerEmotion("Pain")
      UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_13']))
  	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_14']))
	  SV.lot_emolga.chat = 1
	end
  elseif SV.sidequest.quest03 == 3 then
    UI:SetSpeaker(chara)
	UI:SetSpeakerEmotion("Sigh")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_11']))
  elseif SV.lot_emolga.greeted == true then
  local hid = SV.hiddensidequest.celebi
  local powwene = CH('Powwene')
    if hid == 0 then
	  UI:SetSpeaker(chara)
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_1']))
	  UI:SetSpeakerEmotion("Pain")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_2']))
	  if SV.global_quest.StoryProgression < 13 then
	    UI:SetSpeaker(powwene)
		UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_0']))
		UI:SetSpeaker(chara)
		UI:SetSpeakerEmotion("Happy")
	    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_3']))
		SV.hiddensidequest.celebi = 1
      end
    end
	if SV.lot_emolga.talkshrine == false then
	  if hid > 0 and hid < 3 then
	    UI:SetSpeaker(chara)
	    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_4']))
	    if hid == 2 then
		  if SV.global_quest.StoryProgression < 13 then
	        UI:SetSpeaker(powwene)
			UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_2']))
			UI:SetSpeaker(chara)
			UI:SetSpeakerEmotion("Surprised")
		    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_6']))
		    UI:SetSpeaker(powwene)
			UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_3']))
			UI:SetSpeaker(chara)
			UI:SetSpeakerEmotion("Crying")
		    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_7']))
		    UI:SetSpeaker(powwene)
			UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4'], SV.playername))
		  else
		    UI:SetSpeaker(chara)
			UI:SetSpeakerEmotion("Surprised")
			UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_6']))
			UI:SetSpeakerEmotion("Crying")
			UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_7_B']))
		  end
		  SV.lot_emolga.talkshrine = true
	    else
	      UI:SetSpeaker(powwene)
		  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
		  UI:SetSpeaker(chara)
		  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_5']))
	    end
	  end
	else
	  UI:SetSpeaker(chara)
	  UI:SetSpeakerEmotion("Sad")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_8']))
	end
  else
    UI:SetSpeaker(chara)
	UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Emolga_0']))
	SV.lot_emolga.greeted = true
  end
end

return lot_emolga

