--[[
    init.lua
    Created: 06/28/2023 23:21:20
    Description: Autogenerated script file for the map tutorial.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local tutorial = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---tutorial.Init(map)
--Engine callback function
function tutorial.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---tutorial.Enter(map)
--Engine callback function
function tutorial.Enter(map)

  GAME:FadeIn(20)

end

---tutorial.Exit(map)
--Engine callback function
function tutorial.Exit(map)


end

---tutorial.Update(map)
--Engine callback function
function tutorial.Update(map)


end

---tutorial.GameSave(map)
--Engine callback function
function tutorial.GameSave(map)


end

---tutorial.GameLoad(map)
--Engine callback function
function tutorial.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return tutorial

