--[[
    init.lua
    Created: 07/29/2023 10:23:27
    Description: Autogenerated script file for the map td_mixandmatch.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_mixandmatch = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_mixandmatch.Init(zone)
--Engine callback function
function td_mixandmatch.Init(zone)


end

---td_mixandmatch.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_mixandmatch.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_mixandmatch.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_mixandmatch.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_mixandmatch.Rescued(zone, name, mail)
--Engine callback function
function td_mixandmatch.Rescued(zone, name, mail)


end

return td_mixandmatch

