--[[
	init.lua
	Created: 03/14/2023 19:20:01
	Description: Autogenerated script file for the map event_oriental_celebi.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local event_oriental_celebi = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--	  local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_oriental_celebi.Init
--Engine callback function
function event_oriental_celebi.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_oriental_celebi.Enter
--Engine callback function
function event_oriental_celebi.Enter(map)

  COMMONEX.PlayerCutscene()
  local ohchan = CH('Oh-Chan')
  local celebi = CH('Celebi')
  local powwene = CH('Powwene')
  local player = CH('PLAYER')
  GAME:CutsceneMode(true)
  if SV.hiddensidequest.celebi == 2 then
	GROUND:Hide('Shrine')
	GROUND:RemoveCharacter('Oh-Chan')
	GROUND:RemoveCharacter('Celebi')
	GROUND:TeleportTo(player, 155, 205, Direction.Right)
	GROUND:TeleportTo(powwene, 195, 205, Direction.Left)
	GAME:FadeIn(20)
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Worried")
	UI:ChoiceMenuYesNo(STRINGS:Format(MapStrings['Powwene_9']),true)
	UI:WaitForChoice()
	result = UI:ChoiceResult()
	if result then
	  UI:SetSpeakerEmotion("Sigh")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_10_Y']))
	else
	  UI:SetSpeakerEmotion("Sad")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_10_N']))
	end
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_11']))
	GAME:FadeOut(false,60)
	GAME:CutsceneMode(false)
	COMMONEX.PointIncrease(5)
	SV.hiddensidequest.celebi = 3
	COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'td_throwback_land', -1, 2, 2)
  else
	GROUND:Hide('Celebi')
	GROUND:Hide('Shrine_Broken')
	GAME:FadeIn(20)
	local coro1 = TASK:BranchCoroutine(function() event_oriental_celebi.Move1(powwene) end)
	GROUND:MoveInDirection(player, Direction.Up, 48, false, 1)
	TASK:JoinCoroutines({coro1})
	UI:SetSpeaker(ohchan)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_0']))
	GROUND:CharSetAnim(ohchan, "Special0", true)
	UI:SetSpeakerEmotion("Joyous")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_1']))
	GROUND:CharEndAnim(ohchan)
	GROUND:MoveToPosition(ohchan, 172, 57, false, 2)
	GROUND:RemoveCharacter('Oh-Chan')
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Inspired")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_0']))
	GROUND:CharSetEmote(player, "question", 1)
	SOUND:PlayBattleSE("EVT_Emote_Confused")
	GAME:WaitFrames(30)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
	local coro1 = TASK:BranchCoroutine(function() event_oriental_celebi.Shock(player) end)
	GROUND:MoveToPosition(powwene, 172, 170, false, 2)
	GROUND:EntTurn(powwene, Direction.Up)
	TASK:JoinCoroutines({coro1})
	UI:SetSpeakerEmotion("Shouting")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_2']))
	GROUND:CharSetAnim(powwene, "Attack", false)
	SOUND:PlayBattleSE("DUN_Attack")
	GAME:WaitFrames(15)
	GROUND:Unhide('Shrine_Broken')
	GROUND:Hide('Shrine')
	SOUND:PlayBattleSE("TB_EVT_BuildingDestroyed")
	UI:SetSpeakerEmotion("Worried")
	UI:BeginChoiceMenu(STRINGS:Format(MapStrings['Powwene_3']),
	{STRINGS:Format(MapStrings['Answer_1_A']),
	STRINGS:Format(MapStrings['Answer_1_B']),
	STRINGS:Format(MapStrings['Answer_1_C']),
	STRINGS:Format(MapStrings['Answer_1_D'])}, 1, 1)
	UI:WaitForChoice()
	result = UI:ChoiceResult()
	GROUND:CharAnimateTurn(powwene, Direction.Down, 4, false)
	if result == 1 then
	  UI:SetSpeakerEmotion("Surprised")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4_A']))
	end
	if result == 2 then
	  UI:SetSpeakerEmotion("Worried")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4_B']))
	end
	if result == 3 then
	  UI:SetSpeakerEmotion("Worried")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4_C']))
	end
	if result == 4 then
	  UI:SetSpeakerEmotion("Worried")
	  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4_D']))
	end
	GROUND:CharSetAnim(player, "Walk", true)
	GAME:WaitFrames(60)
	GROUND:CharEndAnim(player)
	GAME:WaitFrames(30)
	GROUND:CharSetEmote(powwene, "exclaim", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_5'], SV.playername))
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_6']))
	local coro1 = TASK:BranchCoroutine(function() event_oriental_celebi.Shock(powwene) end)
	local coro2 = TASK:BranchCoroutine(function() event_oriental_celebi.Shock(player) end)
	UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Celebi_0']))
	TASK:JoinCoroutines({coro1,coro2})
	SOUND:PlayBattleSE("DUN_Aurora_Beam_2")
	GAME:FadeOut(true,10)
	celebi.CollisionDisabled = true
	GROUND:Unhide('Celebi')
	GAME:FadeIn(10)
	GROUND:AnimateInDirection(powwene, "Hurt", Direction.Up, Direction.Down, 15, 3, 2)
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Teary-Eyed")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_7']))
	UI:SetSpeaker(celebi)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Celebi_1']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Crying")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_8']))
	GAME:FadeOut(false,20)
	SV.hiddensidequest.celebi = 2
	GAME:CutsceneMode(false)
	GAME:ContinueDungeon('td_oriental', 1, 0, 0)
  end

end

---event_oriental_celebi.Exit
--Engine callback function
function event_oriental_celebi.Exit(map)


end

---event_oriental_celebi.Update
--Engine callback function
function event_oriental_celebi.Update(map)


end

---event_oriental_celebi.GameSave
--Engine callback function
function event_oriental_celebi.GameSave(map)


end

---event_oriental_celebi.GameLoad
--Engine callback function
function event_oriental_celebi.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function event_oriental_celebi.Move1(character)
  GROUND:MoveInDirection(character, Direction.Up, 48, false, 1)
end

function event_oriental_celebi.Shock(character)
  GROUND:CharSetEmote(character, "shock", 1)
  SOUND:PlayBattleSE("EVT_Emote_Shock_2")
end

return event_oriental_celebi

