--[[
    init.lua
    Created: 03/28/2023 10:52:42
    Description: Autogenerated script file for the map spiderlife_baseno1.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local spiderlife_baseno1 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---spiderlife_baseno1.Init(map)
--Engine callback function
function spiderlife_baseno1.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---spiderlife_baseno1.Enter(map)
--Engine callback function
function spiderlife_baseno1.Enter(map)

  GAME:FadeIn(20)

end

---spiderlife_baseno1.Exit(map)
--Engine callback function
function spiderlife_baseno1.Exit(map)


end

---spiderlife_baseno1.Update(map)
--Engine callback function
function spiderlife_baseno1.Update(map)


end

---spiderlife_baseno1.GameSave(map)
--Engine callback function
function spiderlife_baseno1.GameSave(map)


end

---spiderlife_baseno1.GameLoad(map)
--Engine callback function
function spiderlife_baseno1.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return spiderlife_baseno1

