--[[
    init.lua
    Created: 08/01/2023 11:15:20
    Description: Autogenerated script file for the map aqua_mirage_boss.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local aqua_mirage_boss = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---aqua_mirage_boss.Init(map)
--Engine callback function
function aqua_mirage_boss.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---aqua_mirage_boss.Enter(map)
--Engine callback function
function aqua_mirage_boss.Enter(map)

  GAME:FadeIn(20)

end

---aqua_mirage_boss.Exit(map)
--Engine callback function
function aqua_mirage_boss.Exit(map)


end

---aqua_mirage_boss.Update(map)
--Engine callback function
function aqua_mirage_boss.Update(map)


end

---aqua_mirage_boss.GameSave(map)
--Engine callback function
function aqua_mirage_boss.GameSave(map)


end

---aqua_mirage_boss.GameLoad(map)
--Engine callback function
function aqua_mirage_boss.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return aqua_mirage_boss

