--[[
    init.lua
    Created: 06/11/2023 10:35:57
    Description: Autogenerated script file for the map amusement_activitieshub.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local amusement_activitieshub = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---amusement_activitieshub.Init(map)
--Engine callback function
function amusement_activitieshub.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---amusement_activitieshub.Enter(map)
--Engine callback function
function amusement_activitieshub.Enter(map)

  GAME:FadeIn(20)

end

---amusement_activitieshub.Exit(map)
--Engine callback function
function amusement_activitieshub.Exit(map)


end

---amusement_activitieshub.Update(map)
--Engine callback function
function amusement_activitieshub.Update(map)


end

---amusement_activitieshub.GameSave(map)
--Engine callback function
function amusement_activitieshub.GameSave(map)


end

---amusement_activitieshub.GameLoad(map)
--Engine callback function
function amusement_activitieshub.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return amusement_activitieshub

