--[[
    init.lua
    Created: 09/26/2023 02:25:14
    Description: Autogenerated script file for the map td_thedistantboi.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_thedistantboi = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_thedistantboi.Init(zone)
--Engine callback function
function td_thedistantboi.Init(zone)


end

---td_thedistantboi.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_thedistantboi.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_thedistantboi.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_thedistantboi.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_thedistantboi.Rescued(zone, name, mail)
--Engine callback function
function td_thedistantboi.Rescued(zone, name, mail)


end

return td_thedistantboi

