--[[
    init.lua
    Created: 02/04/2023 06:51:29
    Description: Autogenerated script file for the map event_opening.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local event_opening = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_opening.Init
--Engine callback function
function event_opening.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_opening.Enter
--Engine callback function
function event_opening.Enter(map)

  GAME:FadeIn(20)

end

---event_opening.Exit
--Engine callback function
function event_opening.Exit(map)


end

---event_opening.Update
--Engine callback function
function event_opening.Update(map)


end

---event_opening.GameSave
--Engine callback function
function event_opening.GameSave(map)


end

---event_opening.GameLoad
--Engine callback function
function event_opening.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return event_opening

