--[[
    init.lua
    Created: 03/05/2023 18:46:09
    Description: Autogenerated script file for the map event_tripleboost.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local event_tripleboost = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_tripleboost.Init
--Engine callback function
function event_tripleboost.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_tripleboost.Enter
--Engine callback function
function event_tripleboost.Enter(map)

  GAME:FadeIn(20)

end

---event_tripleboost.Exit
--Engine callback function
function event_tripleboost.Exit(map)


end

---event_tripleboost.Update
--Engine callback function
function event_tripleboost.Update(map)


end

---event_tripleboost.GameSave
--Engine callback function
function event_tripleboost.GameSave(map)


end

---event_tripleboost.GameLoad
--Engine callback function
function event_tripleboost.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return event_tripleboost

