--[[
    init.lua
    Created: 03/28/2023 11:05:44
    Description: Autogenerated script file for the map spiderlife.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local spiderlife = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---spiderlife.Init(map)
--Engine callback function
function spiderlife.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---spiderlife.Enter(map)
--Engine callback function
function spiderlife.Enter(map)

  GAME:FadeIn(20)

end

---spiderlife.Exit(map)
--Engine callback function
function spiderlife.Exit(map)


end

---spiderlife.Update(map)
--Engine callback function
function spiderlife.Update(map)


end

---spiderlife.GameSave(map)
--Engine callback function
function spiderlife.GameSave(map)


end

---spiderlife.GameLoad(map)
--Engine callback function
function spiderlife.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return spiderlife

