--[[
    init.lua
    Created: 12/22/2022 08:17:47
    Description: Autogenerated script file for the map td_childhood_park.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_childhood_park = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---CURZONESCR.Init
--Engine callback function
function td_childhood_park.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_td_childhood_park")
end

---CURZONESCR.EnterSegment
--Engine callback function
function td_childhood_park.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---CURZONESCR.ExitSegment
--Engine callback function
function td_childhood_park.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_td_childhood_park result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  COMMON.ExitDungeonMissionCheck(zone.ID, segmentID)
  if rescue == true then
    COMMON.EndRescue(zone, result, segmentID)
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    if segmentID == 0 then
	  if SV.global_quest.StoryProgression == 10 then
        GAME:EnterGroundMap("event_childhoodpark_bossroom", "Entrance")
	  elseif SV.global_quest.StoryProgression == 11 then
	    GAME:ContinueDungeon('td_childhood_park', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
	  else
	    COMMON.EndDungeonDay(result, 'td_throwback_land', -1, 2, 2)
	  end
    elseif segmentID == 1 and SV.global_quest.StoryProgression == 11 then
	  GAME:EnterGroundMap("event_childhoodpark_bossroom", "Entrance")
	else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end

---CURZONESCR.Rescued
--Engine callback function
function td_childhood_park.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return td_childhood_park

