--[[
    init.lua
    Created: 02/27/2023 15:19:43
    Description: Autogenerated script file for the map td_tinytillies.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_tinytillies = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_tinytillies.Init
--Engine callback function
function td_tinytillies.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_td_tinytillies")
end

---td_tinytillies.EnterSegment
--Engine callback function
function td_tinytillies.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---td_tinytillies.ExitSegment
--Engine callback function
function td_tinytillies.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_td_tinytillies result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  COMMON.ExitDungeonMissionCheck(zone.ID, segmentID)
  if rescue == true then
    COMMON.EndRescue(zone, result, segmentID)
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    if segmentID == 0 then
	  if SV.sidequest.quest03 == 3 then
	    UI:SetSpeaker("Teddiursa", true, "teddiursa", 0, "normal", RogueEssence.Data.Gender.Unknown)
		UI:SetSpeakerEmotion("Crying")
		UI:WaitShowDialogue(STRINGS:Format("You are here, thank God! I believed I would remain here forever lost."))
		UI:SetSpeakerEmotion("Teary-Eyed")
		UI:WaitShowDialogue(STRINGS:Format("Just lead me out of this, this place giving me the creeps!"))
		SV.sidequest.quest03 = 4
		UI:ResetSpeaker()
	  end
      COMMON.EndDungeonDay(result, 'td_throwback_land', -1, 9, 1)
    else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end

---td_tinytillies.Rescued
--Engine callback function
function td_tinytillies.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return td_tinytillies

