--[[
	init.lua
	Created: 01/28/2023 18:25:59
	Description: Autogenerated script file for the map event_childhoodpark_bossroom.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local event_childhoodpark_bossroom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--	  local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_childhoodpark_bossroom.Init
--Engine callback function
function event_childhoodpark_bossroom.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_childhoodpark_bossroom.Enter
--Engine callback function
function event_childhoodpark_bossroom.Enter(map)

  GAME:CutsceneMode(true)
  COMMONEX.PlayerCutscene()
  local powwene = CH('Powwene')
  local player = CH("PLAYER")
  local drifloon = CH('Drifloon_Leader')
  local drifloon1 = CH('Drifloon_1')
  local drifloon2 = CH('Drifloon_2')
  local pichu = CH('Pichu')
  local igglybuff = CH('Igglybuff')
  GAME:FadeIn(20)
  if SV.global_quest.StoryProgression == 11 then
	GROUND:TeleportTo(powwene, 162, 268, Direction.Up)
	GROUND:TeleportTo(player, 136, 268, Direction.Up)
	UI:SetSpeaker(drifloon)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_4']))
	COMMONEX.SmoothRemove("Drifloon_Leader")
	COMMONEX.SmoothRemove("Drifloon_1")
	COMMONEX.SmoothRemove("Drifloon_2")
	local coro1 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move3(pichu) end)
	local coro2 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move3(igglybuff) end)
	local coro3 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move3(CH('Wooper')) end)
	TASK:JoinCoroutines({coro1,coro2,coro3})
	GAME:WaitFrames(48)
	UI:SetSpeaker(pichu)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Pichu_0']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_3']))
	UI:SetSpeaker(pichu)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Pichu_1']))
	UI:SetSpeaker(igglybuff)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Igglybuff_0']))
	UI:SetSpeaker(pichu)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Pichu_2']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_4']))
	UI:SetSpeaker(igglybuff)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Igglybuff_1']))
	COMMONEX.PointIncrease(3)
	SOUND:FadeOutBGM()
	GAME:FadeOut(false,60)
	SV.global_quest.StoryProgression = 12
	GAME:CutsceneMode(false)
	COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'td_throwback_land', -1, 6, 0)
  end
  if SV.global_quest.StoryProgression == 10 then
	local coro1 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move1(powwene) end)
	GROUND:MoveInDirection(player, Direction.Up, 24, false, 1)
	TASK:JoinCoroutines({coro1})
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_0']))
	local coro1 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move2(drifloon) end)
	local coro2 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move2(drifloon1) end)
	local coro3 = TASK:BranchCoroutine(function() event_childhoodpark_bossroom.Move2(drifloon2) end)
	GAME:WaitFrames(32)
	TASK:JoinCoroutines({coro1,coro2,coro3})
	UI:SetSpeaker(drifloon)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_0']))
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_1']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
	UI:SetSpeaker(drifloon)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_2']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_2']))
	UI:SetSpeaker(drifloon)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_3']))
	GAME:FadeOut(false,20)
	GAME:CutsceneMode(false)
	SV.global_quest.StoryProgression = 11
	GAME:ContinueDungeon('td_childhood_park', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
  end

end

---event_childhoodpark_bossroom.Exit
--Engine callback function
function event_childhoodpark_bossroom.Exit(map)


end

---event_childhoodpark_bossroom.Update
--Engine callback function
function event_childhoodpark_bossroom.Update(map)


end

---event_childhoodpark_bossroom.GameSave
--Engine callback function
function event_childhoodpark_bossroom.GameSave(map)


end

---event_childhoodpark_bossroom.GameLoad
--Engine callback function
function event_childhoodpark_bossroom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function event_childhoodpark_bossroom.Move1(character)
  GROUND:MoveInDirection(character, Direction.Up, 24, false, 1)
end

function event_childhoodpark_bossroom.Move2(character)
  GROUND:CharSetEmote(character, "notice", 1)
  GAME:WaitFrames(16)
  GROUND:CharAnimateTurn(character, Direction.Down, 3, true)
end

function event_childhoodpark_bossroom.Move3(character)
  GROUND:MoveInDirection(character, Direction.Down, 48, false, 2)
end

return event_childhoodpark_bossroom

