--[[
    init.lua
    Created: 02/05/2023 06:53:52
    Description: Autogenerated script file for the map stage_theater_backstage.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local stage_theater_backstage = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---stage_theater_backstage.Init
--Engine callback function
function stage_theater_backstage.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---stage_theater_backstage.Enter
--Engine callback function
function stage_theater_backstage.Enter(map)

  GAME:FadeIn(20)

end

---stage_theater_backstage.Exit
--Engine callback function
function stage_theater_backstage.Exit(map)


end

---stage_theater_backstage.Update
--Engine callback function
function stage_theater_backstage.Update(map)


end

---stage_theater_backstage.GameSave
--Engine callback function
function stage_theater_backstage.GameSave(map)


end

---stage_theater_backstage.GameLoad
--Engine callback function
function stage_theater_backstage.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return stage_theater_backstage

