--[[
    init.lua
    Created: 02/13/2023 19:05:53
    Description: Autogenerated script file for the map td_watertomb.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_watertomb = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---CURZONESCR.Init
--Engine callback function
function td_watertomb.Init(zone)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> Init_td_watertomb")
end

---CURZONESCR.EnterSegment
--Engine callback function
function td_watertomb.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---CURZONESCR.ExitSegment
--Engine callback function
function td_watertomb.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_td_watertomb result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  COMMON.ExitDungeonMissionCheck(zone.ID, segmentID)
  if rescue == true then
    COMMON.EndRescue(zone, result, segmentID)
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    if segmentID == 0 then
      COMMON.EndDungeonDay(result, 'td_throwback_land', -1, 7, 1)
	elseif segmentID == 2 then
	  if SV.global_quest.StoryProgression < 13 then
	    SV.global_quest.StoryProgression = 13
	  end
	  GAME:EnterGroundMap("watertomb_ohchan", "Spawn")
	elseif segmentID == 3 then
	  if SV.global_quest.StoryProgression < 16 then
	    SV.global_quest.StoryProgression = 16
	  end
	  GAME:EnterGroundMap("watertomb_bossroom", "Entrance")
    else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    end
  end
end

---CURZONESCR.Rescued
--Engine callback function
function td_watertomb.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return td_watertomb

