--[[
    init.lua
    Created: 05/19/2023 17:48:39
    Description: Autogenerated script file for the map td_luminous_tangle.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_luminous_tangle = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_luminous_tangle.Init(zone)
--Engine callback function
function td_luminous_tangle.Init(zone)


end

---td_luminous_tangle.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_luminous_tangle.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_luminous_tangle.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_luminous_tangle.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_luminous_tangle.Rescued(zone, name, mail)
--Engine callback function
function td_luminous_tangle.Rescued(zone, name, mail)


end

return td_luminous_tangle

