--[[
    init.lua
    Created: 02/16/2023 18:47:09
    Description: Autogenerated script file for the map tdtrial_onionkuya.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local tdtrial_onionkuya = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---CURZONESCR.Init
--Engine callback function
function CURZONESCR.Init(zone)


end

---CURZONESCR.EnterSegment
--Engine callback function
function CURZONESCR.EnterSegment(zone, rescuing, segmentID, mapID)


end

---CURZONESCR.ExitSegment
--Engine callback function
function CURZONESCR.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---CURZONESCR.Rescued
--Engine callback function
function CURZONESCR.Rescued(zone, name, mail)


end

return tdtrial_onionkuya

