--[[
    init.lua
    Created: 12/31/2022 09:42:09
    Description: Autogenerated script file for the map mysidia_pub.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mysidia_pub = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mysidia_pub.Init
--Engine callback function
function mysidia_pub.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---mysidia_pub.Enter
--Engine callback function
function mysidia_pub.Enter(map)

  GAME:FadeIn(20)

end

---mysidia_pub.Exit
--Engine callback function
function mysidia_pub.Exit(map)


end

---mysidia_pub.Update
--Engine callback function
function mysidia_pub.Update(map)


end

---mysidia_pub.GameSave
--Engine callback function
function mysidia_pub.GameSave(map)


end

---mysidia_pub.GameLoad
--Engine callback function
function mysidia_pub.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mysidia_pub

