--[[
    init.lua
    Created: 09/08/2023 02:40:18
    Description: Autogenerated script file for the map td_lourgus_giant.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_lourgus_giant = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_lourgus_giant.Init(zone)
--Engine callback function
function td_lourgus_giant.Init(zone)


end

---td_lourgus_giant.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_lourgus_giant.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_lourgus_giant.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_lourgus_giant.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_lourgus_giant.Rescued(zone, name, mail)
--Engine callback function
function td_lourgus_giant.Rescued(zone, name, mail)


end

return td_lourgus_giant

