--[[
    init.lua
    Created: 12/26/2022 12:14:25
    Description: Autogenerated script file for the map event_dream.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local event_dream = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---event_dream.Init
--Engine callback function
function event_dream.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---event_dream.Enter
--Engine callback function
function event_dream.Enter(map)

  GAME:FadeIn(20)

end

---event_dream.Exit
--Engine callback function
function event_dream.Exit(map)


end

---event_dream.Update
--Engine callback function
function event_dream.Update(map)


end

---event_dream.GameSave
--Engine callback function
function event_dream.GameSave(map)


end

---event_dream.GameLoad
--Engine callback function
function event_dream.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return event_dream

