--[[
    init.lua
    Created: 12/12/2022 17:52:18
    Description: Autogenerated script file for the map amusement_castle.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local amusement_castle = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---CURMAPSCR.Init
--Engine callback function
function amusement_castle.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---CURMAPSCR.Enter
--Engine callback function
function amusement_castle.Enter(map)
  local vit=CH("Vitaro")
  
  if SV.global_quest.StoryProgression == 4 then
	GAME:CutsceneMode(true)
	GROUND:RemoveCharacter("Powwene")
	local esp=CH("Espurr")
	local mic=CH("Minccino")
	GAME:FadeIn(30)
	GROUND:MoveInDirection(player, Direction.Up, 60, false, 2)
	UI:SetSpeaker(esp)
	UI:SetSpeakerEmotion("Inspired")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Espurr_0']))
	UI:SetSpeaker(vit)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Vitaro_0']))
	UI:SetSpeaker(mic)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Minccino_0']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Minccino_1']))
	UI:SetSpeaker(vit)
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Vitaro_1']))
	GAME:FadeOut(false,20)
	GROUND:RemoveCharacter("Espurr")
	GROUND:RemoveCharacter("Minccino")
	SV.global_quest.StoryProgression = 5
  end
  
  if SV.global_quest.StoryProgression > 4 then
	GROUND:RemoveCharacter("Espurr")
	GROUND:RemoveCharacter("Minccino")
  end
  
  GAME:CutsceneMode(false)
  
  if SV.global_quest.StoryProgression == 5 then
	GROUND:TeleportTo(vit, 244, 220, Direction.Down)
  else
	GROUND:RemoveCharacter("Vitaro")
  end
  
  if SV.global_quest.StoryProgression > 8 then
	GROUND:RemoveCharacter("Pichu")
	GROUND:RemoveCharacter("Drifloon")
  end
  
  if SV.global_quest.StoryProgression == 9 and SV.sidequest.quest00 == 2 and SV.sidequest.quest01 == 2 then
	local powwene=CH('Powwene')
	GAME:CutsceneMode(true)
	powwene.CollisionDisabled = true
	GROUND:TeleportTo(CH('PLAYER'), 330, 362, Direction.Right)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Pichu_1']))
	GAME:FadeIn(20)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_1']))
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_0']))
	GROUND:CharAnimateTurn(powwene, Direction.Down, 2, false)
	GROUND:CharAnimateTurn(CH('PLAYER'), Direction.Up, 2, true)
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_2']))
	GROUND:MoveInDirection(powwene, Direction.Down, 19, false, 1)
	UI:ResetSpeaker()
	GROUND:RemoveCharacter("Powwene")
    local mon_id = RogueEssence.Dungeon.MonsterID("td_powpow", 1, "normal", Gender.Female)
	local p = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 5, "", 0)
	p.Nickname = 'Powwene'
	p.MetAt = "Amusement Castle"
	p.IsFounder = true
	p.OriginalUUID = "specialmember_powwene"
	p.OriginalTeam = "Team Pow-Pow"
	SV.guest_members.powwene = p
	GAME:UnlockDungeon('td_childhood_park')
	COMMONEX.SpecialCharJoined(p,"Powwene",2)
	SV.global_quest.StoryProgression = 10
	GAME:CutsceneMode(false)
  else
	GROUND:RemoveCharacter("Powwene")
  end
  
  if SV.global_quest.StoryProgression < 19 then
	GROUND:RemoveCharacter("Gapori")
	GROUND:RemoveCharacter("Kecleon")
  end
  
  if SV.global_quest.StoryProgression > 17 then
    SOUND:PlayBGM("NadEvent10. Help.ogg", true)
	GROUND:RemoveCharacter("Slowking")
	GROUND:RemoveCharacter("Slowpoke_L")
	GROUND:RemoveCharacter("Slowpoke_R")
	if SV.global_quest.StoryProgression == 19 then
	  GROUND:RemoveCharacter("Misdreavus")
	  GROUND:RemoveCharacter("Zigzagoon")
	  GROUND:Hide("InvasionEvent")
	end
  else
    GROUND:RemoveCharacter("Misdreavus")
	GROUND:RemoveCharacter("Zigzagoon")
	GROUND:RemoveCharacter("Nidoqueen")
	GROUND:RemoveCharacter("Nidorino")
	GROUND:RemoveCharacter("Nidoran_M_1")
	GROUND:RemoveCharacter("Nidoran_M_2")
	GROUND:RemoveCharacter("Nidoran_F_1")
	GROUND:RemoveCharacter("Nidoran_F_2")
	GROUND:Hide("InvasionEvent")
  end
  
  if SV.global_quest.StoryProgression == 19 then
    SV.global_quest.StoryProgression = 20
	GAME:CutsceneMode(true)
	GAME:FadeIn(20)
	CH("PLAYER").CollisionDisabled = true
	GROUND:MoveToPosition(CH("PLAYER"), 246, 184, false, 2)
	GROUND:CharAnimateTurn(CH('PLAYER'), Direction.Up, 2, false)
	local nidoqueen = CH("Nidoqueen")
	local kecleon = CH("Kecleon")
	local gapori = CH("Gapori")
	gapori.CollisionDisabled = true
	kecleon.CollisionDisabled = true
	UI:SetSpeaker(nidoqueen)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_3']))
	UI:SetSpeaker(kecleon)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_0']))
	UI:SetSpeaker(gapori)
    UI:SetSpeakerEmotion("Angry")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_0']))
	UI:SetSpeaker(nidoqueen)
    UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_4']))
	GROUND:MoveInDirection(nidoqueen, Direction.Down, 12, false, 2)
	GROUND:CharSetAnim(nidoqueen, "Attack", false)
	SOUND:PlayBattleSE("DUN_Attack")
	GAME:WaitFrames(15)
	local coro1 = TASK:BranchCoroutine(function() amusement_castle.aaaaaa(gapori) end)
	local coro2 = TASK:BranchCoroutine(function() amusement_castle.aaaaaa(kecleon) end)
	SOUND:PlayBattleSE("TB_Meme_Scream_Gapori")
	TASK:JoinCoroutines({coro1,coro2})
	GROUND:RemoveCharacter("Gapori")
	GROUND:RemoveCharacter("Kecleon")
	GROUND:MoveInDirection(nidoqueen, Direction.Up, 12, false, 2)
	GROUND:CharAnimateTurn(nidoqueen, Direction.Down, 2, true)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_5']))
	GAME:FadeOut(false,20)
	GAME:EnterDungeon('td_throwback_land', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, false, false)
	GAME:CutsceneMode(false)
  else
    GAME:FadeIn(20)
  end

end

---CURMAPSCR.Exit
--Engine callback function
function amusement_castle.Exit(map)


end

---CURMAPSCR.Update
--Engine callback function
function amusement_castle.Update(map)


end

---CURMAPSCR.GameSave
--Engine callback function
function amusement_castle.GameSave(map)


end

---CURMAPSCR.GameLoad
--Engine callback function
function amusement_castle.GameLoad(map)

  if SV.global_quest.StoryProgression > 17 then
    SOUND:PlayBGM("NadEvent10. Help.ogg", true)
  end
  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function amusement_castle.aaaaaa(character)
  GROUND:CharSetEmote(character, "shock", 1)
  SOUND:PlayBattleSE("EVT_Emote_Shock")
  GROUND:AnimateInDirection(character, "Hurt", Direction.Up, Direction.Down, 60, 2, 4)
end

function amusement_castle.InvasionEvent_Touch(obj, activator)
  GAME:UnlockDungeon("td_fieldgarden")
  GAME:UnlockDungeon("td_starlight")
  GAME:UnlockDungeon("td_cobaltcells")
  GROUND:MoveToPosition(CH("PLAYER"), 244, 168, false, 2)
  GAME:MoveCamera(0, -24, 24, true)
  UI:SetSpeaker(CH("Misdreavus"))
  UI:SetSpeakerEmotion("Shouting")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Misdreavus_0']))
  UI:SetSpeaker(CH("Nidoqueen"))
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_0']))
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_1']))
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoqueen_2']))
  UI:SetSpeaker(STRINGS:Format("[color=#00FFFF]Nidorans[color]"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Nidoran_0']))
  UI:SetSpeaker(CH("Zigzagoon"))
  UI:SetSpeakerEmotion("Determined")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Zigzagoon_0']))
  GAME:FadeOut(false,20)
  GAME:EnterGroundMap("amusement_castle_prison", "Entrance")
end

function amusement_castle.Pichu_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Inspired")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Pichu_0']))
end

function amusement_castle.Drifloon_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Drifloon_0']))
end

function amusement_castle.Slowking_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_0']))
end

function amusement_castle.Slowpoke_L_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['SlowpokeL_0']))
end

function amusement_castle.Slowpoke_R_Action(chara, activator)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['SlowpokeR_0']))
end

function amusement_castle.Vitaro_Action(chara, activator)
  if SV.global_quest.StoryProgression == 5 then
	local swk=CH('Slowking')
	GROUND:CharTurnToChar(chara,CH('PLAYER'))
	UI:SetSpeaker(chara)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Vitaro_2']))
	GAME:FadeOut(false,20)
	GAME:CutsceneMode(true)
	COMMONEX.PlayerCutscene()
	GROUND:TeleportTo(chara, 228, 146, Direction.Up)
	GROUND:TeleportTo(CH('PLAYER'), 260, 146, Direction.Up)
	GAME:FadeIn(20)
	UI:SetSpeaker(swk)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_2']))
	local ch = false
	local name = ""
	while not ch do
	name = ""
	while name == "" do
	  UI:NameMenu(STRINGS:FormatKey("INPUT_TEAM_TITLE"), "")
	  UI:WaitForChoice()
	  name = UI:ChoiceResult()
	end
	  UI:ChoiceMenuYesNo(STRINGS:Format(MapStrings['Slowking_3'], name), true)
	  UI:WaitForChoice()
	  ch = UI:ChoiceResult()
	end
	GAME:SetTeamName(name)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_4']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_5']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_6']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_7'], name))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_8']))
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Slowking_9']))
	UI:SetSpeaker(chara)
	GROUND:CharAnimateTurn(chara, Direction.Right, 4, true)
	GROUND:CharAnimateTurn(CH('PLAYER'), Direction.Left, 4, true)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Vitaro_3']))
	GAME:FadeOut(false,20)
	GAME:CutsceneMode(false)
	GROUND:RemoveCharacter("Vitaro")
	GROUND:CharAnimateTurn(CH('PLAYER'), Direction.Down, 0, true)
	GROUND:RefreshPlayer()
	GROUND:TeleportTo(CH('PLAYER'), 244, 160, Direction.Down)
	SV.global_quest.StoryProgression = 6
	GAME:FadeIn(20)
  end
end

function amusement_castle.Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("amusement_park", "entrance_north")
end

function amusement_castle.DungeonStair_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker()
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_0']))
end

return amusement_castle

