--[[
    init.lua
    Created: 02/18/2023 18:16:27
    Description: Autogenerated script file for the map watertomb_ohchan.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local watertomb_ohchan = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---watertomb_ohchan.Init
--Engine callback function
function watertomb_ohchan.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GROUND:RefreshPlayer()

end

---watertomb_ohchan.Enter
--Engine callback function
function watertomb_ohchan.Enter(map)

  if SV.global_quest.StoryProgression == 13 then
    SOUND:PlayBGM("", true)
	COMMONEX.PlayerCutscene()
	local powwene = CH('Powwene')
	local ohchan = CH('OhChan')
	powwene.CollisionDisabled = true
	GAME:CutsceneMode(true)
	GROUND:EntTurn(ohchan, Direction.Down)
	GROUND:TeleportTo(CH("PLAYER"), 157, 73, Direction.UpRight)
	GAME:FadeIn(20)
	UI:SetSpeaker(ohchan)
	UI:SetSpeakerEmotion("Crying")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_3']))
	UI:SetSpeakerEmotion("Shouting")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_4']))
	SOUND:PlayBattleSE("TB_EVT_OhChanDed")
	GROUND:CharWaitAnim(ohchan, "Special1")
	GROUND:RemoveCharacter("OhChan")
	UI:SetSpeaker(powwene)
	UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_1']))
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_12'], SV.playername))
	GROUND:MoveInDirection(powwene, Direction.Left, 32, false, 1)
	GROUND:Hide("Powwene")
	GAME:CutsceneMode(false)
	SV.global_quest.StoryProgression = 14
	GROUND:RefreshPlayer()
  else
	GROUND:Hide("Powwene")
	if SV.global_quest.StoryProgression > 13 then
	  GROUND:RemoveCharacter("OhChan")
	  SOUND:PlayBGM("", true)
	end
	GAME:FadeIn(20)
  end

end

---watertomb_ohchan.Exit
--Engine callback function
function watertomb_ohchan.Exit(map)


end

---watertomb_ohchan.Update
--Engine callback function
function watertomb_ohchan.Update(map)


end

---watertomb_ohchan.GameSave
--Engine callback function
function watertomb_ohchan.GameSave(map)


end

---watertomb_ohchan.GameLoad
--Engine callback function
function watertomb_ohchan.GameLoad(map)

  if SV.global_quest.StoryProgression > 12 then
    SOUND:PlayBGM("", true)
  end
  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function watertomb_ohchan.Exit_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:ContinueDungeon('td_watertomb', 1, 7, 0)
end

function watertomb_ohchan.OhChan_Action(chara, activator)
  local powwene = CH('Powwene')
  GAME:CutsceneMode(true)
  GROUND:CharTurnToChar(chara,CH('PLAYER'))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_0']))
  UI:SetSpeaker(powwene)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Powwene_0']))
  UI:SetSpeaker(chara)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_1']))
  UI:SetSpeakerEmotion("Joyous")
  GROUND:CharSetAnim(chara, "Special0", true)
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['OhChan_2']))
  GAME:FadeOut(false, 20)
  GAME:ContinueDungeon('td_watertomb', 2, 0, 0)
  GAME:CutsceneMode(false)
end

return watertomb_ohchan