--[[
    init.lua
    Created: 09/08/2023 02:44:01
    Description: Autogenerated script file for the map td_antimatter_plaza.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_antimatter_plaza = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_antimatter_plaza.Init(zone)
--Engine callback function
function td_antimatter_plaza.Init(zone)


end

---td_antimatter_plaza.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_antimatter_plaza.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_antimatter_plaza.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_antimatter_plaza.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_antimatter_plaza.Rescued(zone, name, mail)
--Engine callback function
function td_antimatter_plaza.Rescued(zone, name, mail)


end

return td_antimatter_plaza

