--[[
    init.lua
    Created: 06/12/2023 01:56:42
    Description: Autogenerated script file for the map td_cobaltcells.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_cobaltcells = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_cobaltcells.Init(zone)
--Engine callback function
function td_cobaltcells.Init(zone)


end

---td_cobaltcells.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_cobaltcells.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_cobaltcells.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_cobaltcells.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_cobaltcells.Rescued(zone, name, mail)
--Engine callback function
function td_cobaltcells.Rescued(zone, name, mail)


end

return td_cobaltcells

