--[[
    init.lua
    Created: 01/07/2023 15:07:41
    Description: Autogenerated script file for the map childhood_park.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local childhood_park = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---childhood_park.Init
--Engine callback function
function childhood_park.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---childhood_park.Enter
--Engine callback function
function childhood_park.Enter(map)

  GAME:FadeIn(20)

end

---childhood_park.Exit
--Engine callback function
function childhood_park.Exit(map)


end

---childhood_park.Update
--Engine callback function
function childhood_park.Update(map)


end

---childhood_park.GameSave
--Engine callback function
function childhood_park.GameSave(map)


end

---childhood_park.GameLoad
--Engine callback function
function childhood_park.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return childhood_park

