--[[
    init.lua
    Created: 05/01/2023 09:56:49
    Description: Autogenerated script file for the map amusement_castle_prison.
]]--
-- Commonly included lua functions and data
require 'common'
require 'commonex'

-- Package name
local amusement_castle_prison = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---amusement_castle_prison.Init(map)
--Engine callback function
function amusement_castle_prison.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()

end

---amusement_castle_prison.Enter(map)
--Engine callback function
function amusement_castle_prison.Enter(map)

  GAME:CutsceneMode(true)
  local player = CH("PLAYER")
  GROUND:Hide("Kecleon")
  if SV.global_quest.StoryProgression == 18 then
    SV.amusement_castle_prison =
	{
	  noctowl = false
	}
	SV.checkpoint = 
	{
	  Zone    = 'td_throwback_land', Segment  = -1,
	  Map  = 10, Entry  = 0
	}
    GROUND:TeleportTo(CH('PLAYER'), 72, 144, Direction.Down)
	GROUND:CharSetAnim(player,"Sleep",true)
	GAME:FadeIn(75)
	GAME:WaitFrames(40)
	GROUND:CharEndAnim(player)
	GAME:WaitFrames(40)
	GROUND:CharSetEmote(player, "question", 1)
	SOUND:PlayBattleSE("EVT_Emote_Confused")
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Left, 5, false)
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Right, 5, true)
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurn(player, Direction.Down, 5, false)
	GAME:WaitFrames(60)
	GROUND:CharSetEmote(player, "sweating", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GAME:WaitFrames(120)
  else
    if SV.global_quest.StoryProgression > 20 then
	  GROUND:Hide("Block_2")
	  GROUND:RemoveCharacter("Misdreavus")
	  GROUND:RemoveCharacter("Zigzagoon")
	end
    GROUND:Hide("Block_1")
	GROUND:RemoveCharacter("Kecleon")
	GROUND:RemoveCharacter("Gapori")
	GROUND:Hide("Block")
	if SV.amusement_castle_prison.noctowl == true then
	  GROUND:Hide("PassThrough")
	  GROUND:TeleportTo(CH("Noctowl"), 460, 237, Direction.Left)
	end
  end
  TASK:StartScriptLocalCoroutine(function() amusement_castle_prison.MusicChange() end)
  GAME:CutsceneMode(false)
  if SV.wipedout == true then
    GROUND:TeleportTo(CH('PLAYER'), 72, 144, Direction.Down)
	GAME:FadeIn(30)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_0']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Message_1']))
	SV.wipedout = false
  end
  GAME:FadeIn(30)
  
end

---amusement_castle_prison.Exit(map)
--Engine callback function
function amusement_castle_prison.Exit(map)


end

---amusement_castle_prison.Update(map)
--Engine callback function
function amusement_castle_prison.Update(map)


end

---amusement_castle_prison.GameSave(map)
--Engine callback function
function amusement_castle_prison.GameSave(map)


end

---amusement_castle_prison.GameLoad(map)
--Engine callback function
function amusement_castle_prison.GameLoad(map)

  TASK:StartScriptLocalCoroutine(function() amusement_castle_prison.MusicChange() end)
  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function amusement_castle_prison.MusicChange()
  if SV.global_quest.StoryProgression < 21 then
    SOUND:PlayBGM("NadEvent07. Deception.ogg", true)
  elseif SV.global_quest.StoryProgression < 99 then
    SOUND:PlayBGM("Nad120. Trouble at Night.ogg", true)
  else
    SOUND:PlayBGM("Nad119. Royal Palace.ogg", true)
  end
end

function amusement_castle_prison.Assembly_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker()
  COMMON.ShowTeamAssemblyMenu(obj, COMMON.RespawnAllies)
end

function amusement_castle_prison.Storage_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON:ShowTeamStorageMenu()
end

function amusement_castle_prison.Block_1_Action(obj, activator)
  if SV.global_quest.StoryProgression == 18 then
    local gapori = CH("Gapori")
	local kecleon = CH("Kecleon")
	local player = CH("PLAYER")
    SV.global_quest.StoryProgression = 19
	GAME:CutsceneMode(true)
	gapori.CollisionDisabled = true
	kecleon.CollisionDisabled = true
	GROUND:MoveToPosition(gapori, 147, 125, false, 2)
	GAME:WaitFrames(30)
	GROUND:AnimateInDirection(gapori, "Walk", Direction.Left, Direction.Right, 24, 1, 1)
	GROUND:CharWaitAnim(gapori, "Rotate")
	GROUND:MoveToPosition(gapori, 99, 146, true, 4)
	GAME:WaitFrames(30)
	GROUND:CharSetEmote(gapori, "sweating", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GAME:WaitFrames(60)
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_0']))
	GROUND:CharSetEmote(player, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	GROUND:MoveToPosition(player, 77, 163, false, 2)
	GROUND:CharTurnToCharAnimated(player, gapori, 4)
	GROUND:CharTurnToCharAnimated(gapori, player, 4)
	UI:SetSpeakerEmotion("Surprised")
	choices = {STRINGS:Format(MapStrings['Answer_0_A']),
    STRINGS:Format(MapStrings['Answer_0_B'])}
	UI:BeginChoiceMenu(STRINGS:Format(MapStrings['Gapori_1']), choices, 1, 3)
	UI:WaitForChoice()
	ch = UI:ChoiceResult()
	if ch == 1 then
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_2_A']))
	else
	UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_2_B']))
	end
	GAME:WaitFrames(30)
	GROUND:CharSetEmote(gapori, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_3']))
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_4']))
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_5']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_6']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_7']))
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurn(gapori, Direction.UpRight, 8, false)
	GAME:WaitFrames(30)
	GROUND:CharSetEmote(gapori, "sweatdrop", 1)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GAME:WaitFrames(60)
	GROUND:CharTurnToCharAnimated(gapori, player, 4)
	GAME:WaitFrames(30)
	COMMONEX.CharacterIntroduction('Introduction_Gapori')
	gapori.Data.Nickname = 'Gapori'
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Normal")
	choices = {STRINGS:Format(MapStrings['Answer_1_A']),
    STRINGS:Format(MapStrings['Answer_1_B'])}
	UI:BeginChoiceMenu(STRINGS:Format(MapStrings['Gapori_8']), choices, 1, 3)
	UI:WaitForChoice()
	ch = UI:ChoiceResult()
	if ch == 1 then
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_9_A']))
	else
	UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_9_B']))
	end
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_10']))
	choices = {STRINGS:Format(MapStrings['Answer_2_A']),
    STRINGS:Format(MapStrings['Answer_2_B'])}
	UI:BeginChoiceMenu(STRINGS:Format(MapStrings['Gapori_11']), choices, 1, 3)
	UI:WaitForChoice()
	ch = UI:ChoiceResult()
	UI:SetSpeakerEmotion("Determined")
	if ch == 1 then
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_12_A']))
	else
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_12_B']))
	end
	GAME:WaitFrames(30)
	GROUND:CharSetEmote(gapori, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_13']))
	UI:SetSpeakerEmotion("Joyous")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_14']))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_15']))
	GAME:FadeOut(true,20)
	GROUND:Hide("Block_1")
	GROUND:Hide("Block")
	GAME:FadeIn(20)
	GROUND:CharSetEmote(player, "shock", 1)
	GROUND:CharSetEmote(gapori, "shock", 1)
	SOUND:PlayBattleSE("EVT_Emote_Shock")
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurn(gapori, Direction.Down, 3, true)
	GROUND:CharAnimateTurn(player, Direction.Down, 3, false)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_16']))
	UI:SetSpeaker(STRINGS:Format("\\uE040"), true, "", -1, "", RogueEssence.Data.Gender.Unknown)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_0']))
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_17']))
	GROUND:Unhide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Hide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Unhide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Hide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Unhide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Hide("Kecleon")
	GAME:WaitFrames(5)
	GROUND:Unhide("Kecleon")
	GROUND:MoveInDirection(kecleon, Direction.Left, 24, false, 2)
	GROUND:MoveToPosition(kecleon, 92, 202, false, 2)
	GROUND:CharTurnToCharAnimated(kecleon, gapori, 4)
	UI:SetSpeaker(kecleon)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_1']))
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_18']))
	UI:SetSpeaker(kecleon)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_2']))
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_2-1']))
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_19']))
	UI:SetSpeaker(kecleon)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_3']))
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_20']))
	UI:SetSpeaker(kecleon)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_4']))
	GROUND:CharTurnToCharAnimated(kecleon, player, 4)
	GAME:WaitFrames(60)
	GROUND:CharSetEmote(kecleon, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Kecleon_5']))
	GROUND:MoveToPosition(kecleon, 99, 218, true, 4)
	GROUND:MoveInDirection(kecleon, Direction.Right, 79, true, 4)
	GROUND:RemoveCharacter("Kecleon")
	GROUND:CharSetEmote(gapori, "shock", 1)
	SOUND:PlayBattleSE("EVT_Emote_Shock")
	GAME:WaitFrames(30)
	UI:SetSpeaker(gapori)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Gapori_21']))
	GROUND:MoveToPosition(gapori, 99, 218, true, 4)
	GROUND:MoveInDirection(gapori, Direction.Right, 79, true, 4)
	GROUND:RemoveCharacter("Gapori")
	GAME:CutsceneMode(false)
  end
end

function amusement_castle_prison.PassThrough_Touch(obj, activator)
  if SV.amusement_castle_prison.noctowl == false then
    local noc = CH("Noctowl")
	GROUND:CharSetEmote(noc, "notice", 1)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GAME:WaitFrames(30)
	UI:SetSpeaker(noc)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Noctowl_0'], SV.playername))
	GROUND:MoveInDirection(noc, Direction.Up, 16, false, 2)
	GROUND:CharTurnToCharAnimated(noc, CH("PLAYER"), 4)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Noctowl_1']))
	GROUND:MoveInDirection(noc, Direction.Right, 12, false, 2)
	GROUND:CharTurnToCharAnimated(noc, CH("PLAYER"), 4)
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['Noctowl_2']))
	GROUND:Hide("PassThrough")
	GAME:UnlockDungeon('td_amusement_dungeon')
	SV.amusement_castle_prison.noctowl = true
  end
end

function amusement_castle_prison.Noctowl_Action(chara, activator)
  UI:SetSpeaker(chara)
  UI:SetSpeakerEmotion("Happy")
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Noctowl_2']))
end

function amusement_castle_prison.Exit_Touch(obj, activator)
  if SV.global_quest.StoryProgression > 21 then
    GAME:FadeOut(false,20)
	GAME:EnterGroundMap("amusement_castle_ruins", "EntrancefromDungeon")
  else
    UI:ResetSpeaker()
    UI:ChoiceMenuYesNo(STRINGS:Format(MapStrings['Message_2']), false)
    UI:WaitForChoice()
    ch = UI:ChoiceResult()
    if ch then
      GAME:FadeOut(false,20)
	  if SV.global_quest.StoryProgression == 20 then
		GAME:EnterDungeon('td_throwback_land', 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, false, false)
	  else
	    GAME:EnterGroundMap("amusement_castle", "EntrancefromDungeon")
	  end
    end
  end
end

function amusement_castle_prison.DungeonEntrance_Touch(obj, activator)
  local dungeon_entrances = {'td_amusement_dungeon'}
  local ground_entrances = {}
  COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

function amusement_castle_prison.Block_2_Action(obj, activator)
  
end

function amusement_castle_prison.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate4_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate5_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate6_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function amusement_castle_prison.Teammate7_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return amusement_castle_prison

