--[[
    init.lua
    Created: 08/28/2023 11:58:13
    Description: Autogenerated script file for the map td_hauntedzone.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local td_hauntedzone = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---td_hauntedzone.Init(zone)
--Engine callback function
function td_hauntedzone.Init(zone)


end

---td_hauntedzone.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function td_hauntedzone.EnterSegment(zone, rescuing, segmentID, mapID)


end

---td_hauntedzone.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function td_hauntedzone.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---td_hauntedzone.Rescued(zone, name, mail)
--Engine callback function
function td_hauntedzone.Rescued(zone, name, mail)


end

return td_hauntedzone

