--[[
    init.lua
    Created: 01/06/2023 09:25:56
    Description: Autogenerated script file for the map playerkingdom.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local playerkingdom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---playerkingdom.Init
--Engine callback function
function playerkingdom.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---playerkingdom.Enter
--Engine callback function
function playerkingdom.Enter(map)

  GAME:FadeIn(20)

end

---playerkingdom.Exit
--Engine callback function
function playerkingdom.Exit(map)


end

---playerkingdom.Update
--Engine callback function
function playerkingdom.Update(map)


end

---playerkingdom.GameSave
--Engine callback function
function playerkingdom.GameSave(map)


end

---playerkingdom.GameLoad
--Engine callback function
function playerkingdom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return playerkingdom

