--[[
    init.lua
    Created: 04/26/2023 11:04:56
    Description: Autogenerated script file for the map mythical_temple.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mythical_temple = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mythical_temple.Init(map)
--Engine callback function
function mythical_temple.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---mythical_temple.Enter(map)
--Engine callback function
function mythical_temple.Enter(map)

  GAME:FadeIn(20)

end

---mythical_temple.Exit(map)
--Engine callback function
function mythical_temple.Exit(map)


end

---mythical_temple.Update(map)
--Engine callback function
function mythical_temple.Update(map)


end

---mythical_temple.GameSave(map)
--Engine callback function
function mythical_temple.GameSave(map)


end

---mythical_temple.GameLoad(map)
--Engine callback function
function mythical_temple.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mythical_temple

